### ISSUE TITLE
Basic Typescript example -> ERROR: 13 Internal: Received RST_STREAM with code 0

### ISSUE THREAD

**Issue by RyanWilkins** [rpcpool/yellowstone-grpc#296]
Hoping someone can guide me on getting a basic working example. I've struggled for a few hours with the same error message. My setup is VS Code, Typescript, package is installed via npm.

Here is my basic code:

```
import Client from "@triton-one/yellowstone-grpc";

const client = new Client.default("https://api.rpcpool.com:443", undefined);

const version = await client.getVersion(); // gets the version information
console.log(version);
```

And here is the error I receive with my personal drives stripped out:

```
node:internal/process/esm_loader:34
      internalBinding('errors').triggerUncaughtException(
                                ^

Error: 13 INTERNAL: Received RST_STREAM with code 0
    at callErrorFromStatus (/path/to/project/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/path/to/project/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at Object.onReceiveStatus (/path/to/project/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/path/to/project/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /path/to/project/node_modules/@grpc/grpc-js/build/src/resolving-call.js:99:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/path/to/project/node_modules/@grpc/grpc-js/build/src/client.js:160:32)
    at ServiceClientImpl.getVersion (/path/to/project/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /path/to/project/node_modules/@package-name/dist/index.js:253:43
    at new Promise (<anonymous>)
    at Client.<anonymous> (/path/to/project/node_modules/@package-name/dist/index.js:252:50)
    at step (/path/to/project/node_modules/@package-name/dist/index.js:47:23)
    at Object.next (/path/to/project/node_modules/@package-name/dist/index.js:28:53)
    at /path/to/project/node_modules/@package-name/dist/index.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (/path/to/project/node_modules/@package-name/dist/index.js:18:12) {
  code: 13,
  details: 'Received RST_STREAM with code 0',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
```

I've tried many different RPC links. My Quicknode link is showing Status 200 when I run the code (which I believe is consistent with RST_STREAM code 0).

**Comment by fanatid** [comment]
To use gRPC hosted by Triton you need to set `x-token`. What do you mean under quicknode link?

**Comment by RyanWilkins** [comment]
Hello, it's possible I'm misunderstanding what the input should be into the Client class. I tried a few public Solana RPC urls (such as `"https://api.rpcpool.com:443"` in my example) and one from my paid QuickNode account which I know works with solana web3.js. I understood xtoken to be the authentication which could be undefined if not needed? Let me know otherwise and thanks for the help.

**Comment by RyanWilkins** [comment]
Think I figured it out! Didn't realize this package was for a specific paid RPC service and not generic use for any Solana RPC. I followed here from the Raydium docs (https://github.com/raydium-io/raydium-sdk-V1-demo/blob/master/src/subNewAmmPool.ts). Interesting their examples don't use something more open to individuals.

**Comment by fanatid** [comment]
QuickNode can provide gRPC too, just ask them to load the geyser plugin on their RPC nodes.
