### ISSUE TITLE
Error: 8 RESOURCE_EXHAUSTED: Received message larger than max (2065853043 vs 67108864)

### ISSUE THREAD

**Issue by seslly** [rpcpool/yellowstone-grpc#421]
I've been seeing a similar error in my code so I tested out using the basic typescript example code. I saw there was [another issue](https://github.com/rpcpool/yellowstone-grpc/issues/400) where someone was seeing a similar error but as a result of using `bun` instead of node. I'm using nodejs 22.8.0 but also tried on 18.20.0.

It says it's receiving a message size of about 2gb for the system clock subscribe? Not sure what to do but would appreciate any help. I'm using a devnet endpoint currently in my testing.

```
npm start -- --endpoint https://api.rpcpool.com \
  --x-token <token> \
  subscribe \
  --accounts --accounts-account SysvarC1ock11111111111111111111111111111111

> yellowstone-grpc-client-example-ts@1.0.0 start
> npm run build && node dist/client.js --endpoint https://api.rpcpool.com --x-token <token> subscribe --accounts --accounts-account SysvarC1ock11111111111111111111111111111111


> yellowstone-grpc-client-example-ts@1.0.0 build
> tsc -p .

node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^

Error: 8 RESOURCE_EXHAUSTED: Received message larger than max (2065853043 vs 67108864)
    at callErrorFromStatus (/Users/seslly/github/yellowstone-grpc/examples/typescript/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/Users/seslly/github/yellowstone-grpc/examples/typescript/node_modules/@grpc/grpc-js/build/src/client.js:421:73)
    at Object.onReceiveStatus (/Users/seslly/github/yellowstone-grpc/examples/typescript/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /Users/seslly/github/yellowstone-grpc/examples/typescript/node_modules/@grpc/grpc-js/build/src/resolving-call.js:129:78
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
for call at
    at ServiceClientImpl.makeBidiStreamRequest (/Users/seslly/github/yellowstone-grpc/examples/typescript/node_modules/@grpc/grpc-js/build/src/client.js:405:32)
    at ServiceClientImpl.subscribe (/Users/seslly/github/yellowstone-grpc/examples/typescript/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at Client.<anonymous> (/Users/seslly/github/yellowstone-grpc/examples/typescript/node_modules/@triton-one/yellowstone-grpc/dist/index.js:107:63)
    at step (/Users/seslly/github/yellowstone-grpc/examples/typescript/node_modules/@triton-one/yellowstone-grpc/dist/index.js:47:23)
    at Object.next (/Users/seslly/github/yellowstone-grpc/examples/typescript/node_modules/@triton-one/yellowstone-grpc/dist/index.js:28:53)
    at /Users/seslly/github/yellowstone-grpc/examples/typescript/node_modules/@triton-one/yellowstone-grpc/dist/index.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/seslly/github/yellowstone-grpc/examples/typescript/node_modules/@triton-one/yellowstone-grpc/dist/index.js:18:12)
    at Client.subscribe (/Users/seslly/github/yellowstone-grpc/examples/typescript/node_modules/@triton-one/yellowstone-grpc/dist/index.js:104:16)
    at /Users/seslly/github/yellowstone-grpc/examples/typescript/dist/client.js:129:53 {
  code: 8,
  details: 'Received message larger than max (2065853043 vs 67108864)',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}

Node.js v22.8.0
```

if i set the message size really high then i just see a Call Cancelled
"grpc.max_receive_message_length": 3000 * 1024 * 1024"
```
npm start -- --endpoint https://api.rpcpool.com \
  --x-token <token> \
  subscribe \
  --accounts --accounts-account SysvarC1ock11111111111111111111111111111111

> yellowstone-grpc-client-example-ts@1.0.0 start
> npm run build && node dist/client.js --endpoint https://api.rpcpool.com --x-token <token> subscribe --accounts --accounts-account SysvarC1ock11111111111111111111111111111111


> yellowstone-grpc-client-example-ts@1.0.0 build
> tsc -p .

node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^

Error: 1 CANCELLED: Call cancelled
    at callErrorFromStatus (/Users/seslly/github/yellowstone-grpc/examples/typescript/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/Users/seslly/github/yellowstone-grpc/examples/typescript/node_modules/@grpc/grpc-js/build/src/client.js:421:73)
    at Object.onReceiveStatus (/Users/seslly/github/yellowstone-grpc/examples/typescript/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /Users/seslly/github/yellowstone-grpc/examples/typescript/node_modules/@grpc/grpc-js/build/src/resolving-call.js:129:78
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
for call at
    at ServiceClientImpl.makeBidiStreamRequest (/Users/seslly/github/yellowstone-grpc/examples/typescript/node_modules/@grpc/grpc-js/build/src/client.js:405:32)
    at ServiceClientImpl.subscribe (/Users/seslly/github/yellowstone-grpc/examples/typescript/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at Client.<anonymous> (/Users/seslly/github/yellowstone-grpc/examples/typescript/node_modules/@triton-one/yellowstone-grpc/dist/index.js:107:63)
    at step (/Users/seslly/github/yellowstone-grpc/examples/typescript/node_modules/@triton-one/yellowstone-grpc/dist/index.js:47:23)
    at Object.next (/Users/seslly/github/yellowstone-grpc/examples/typescript/node_modules/@triton-one/yellowstone-grpc/dist/index.js:28:53)
    at /Users/seslly/github/yellowstone-grpc/examples/typescript/node_modules/@triton-one/yellowstone-grpc/dist/index.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/seslly/github/yellowstone-grpc/examples/typescript/node_modules/@triton-one/yellowstone-grpc/dist/index.js:18:12)
    at Client.subscribe (/Users/seslly/github/yellowstone-grpc/examples/typescript/node_modules/@triton-one/yellowstone-grpc/dist/index.js:104:16)
    at /Users/seslly/github/yellowstone-grpc/examples/typescript/dist/client.js:129:53 {
  code: 1,
  details: 'Call cancelled',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}

Node.js v22.8.0

**Comment by seslly** [comment]
looks like it was an issue with my endpoint/creds!
